[package]
name = "usb_picoboot_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
async-io = "2.3.4"
bincode = "1.3.3"
futures-lite = "2.3.0"
nusb = "0.1.10"
rusb = "0.9.4"
serde = { version = "1.0.207", features = ["serde_derive"] }
uf2-decode = "0.2.0"
